#!/bin/bash

set -e

echo "🚀 Obsidian Bot Doppler Setup"
echo "============================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() {
    local status=$1
    local message=$2
    case $status in
        "OK") echo -e "${GREEN}✅ $message${NC}" ;;
        "WARN") echo -e "${YELLOW}⚠️  $message${NC}" ;;
        "ERROR") echo -e "${RED}❌ $message${NC}" ;;
        "INFO") echo -e "${BLUE}ℹ️  $message${NC}" ;;
    esac
}

print_header() {
    echo -e "\n${BLUE}🔧 $1${NC}"
    echo "================================"
}

# Step 1: Verify Doppler
print_header "Step 1: Doppler Verification"
if ! command -v doppler &> /dev/null; then
    print_status "ERROR" "Doppler CLI not found. Install with: curl -fsSL https://cli.doppler.com/install.sh | sh"
    exit 1
fi

if ! doppler whoami &> /dev/null; then
    print_status "ERROR" "Not logged into Doppler. Run: doppler login"
    exit 1
fi

print_status "OK" "Doppler CLI ready and authenticated"

# Step 2: Interactive Setup
print_header "Step 2: Interactive Environment Setup"

echo -e "${YELLOW}📝 Please provide the following values:${NC}"
echo ""

# Function to prompt for value
prompt_var() {
    local var_name=$1
    local description=$2
    local is_secret=${3:-false}
    
    echo -e "${BLUE}📝 $var_name${NC}"
    echo -e "   $description"
    
    if [ "$is_secret" = "true" ]; then
        read -s -p "   Value: " value
    else
        read -p "   Value: " value
    fi
    
    echo ""
    
    # Set in Doppler (with retry)
    local retries=3
    while [ $retries -gt 0 ]; do
        if doppler secrets set "$var_name" "$value" --plain 2>/dev/null; then
            print_status "OK" "Secret '$var_name' saved to Doppler"
            break
        else
            retries=$((retries - 1))
            if [ $retries -gt 0 ]; then
                print_status "WARN" "Retrying... ($retries attempts left)"
            fi
        fi
    done
    
    if [ $retries -eq 0 ]; then
        print_status "ERROR" "Failed to save '$var_name' to Doppler"
        return 1
    fi
    
    echo ""
}

# Critical variables
print_status "INFO" "Setting up critical variables..."

prompt_var "SESSION_SECRET" "Secret for session encryption" "true"

# AI Configuration
prompt_var "CLOUDFLARE_WORKER_URL" "Cloudflare Worker URL" "false"
prompt_var "ACTIVE_PROVIDER" "Default AI provider (Cloudflare, Gemini, Groq)" "false"

# Telegram Configuration
prompt_var "TELEGRAM_BOT_TOKEN" "Telegram bot token" "true"

# Database
prompt_var "TURSO_DATABASE_URL" "Database URL (file:./obsidian.db or libsql://...)" "false"

# Optional variables
echo ""
print_status "INFO" "Optional configurations (press Enter to skip)..."

# WhatsApp (optional)
read -p "Configure WhatsApp? (y/N): " setup_whatsapp
if [[ "$setup_whatsapp" =~ ^[Yy]$ ]]; then
    print_status "INFO" "Setting up WhatsApp configuration..."
    prompt_var "WHATSAPP_ACCESS_TOKEN" "WhatsApp Business API access token" "true"
    prompt_var "WHATSAPP_VERIFY_TOKEN" "Webhook verification token" "true"
    prompt_var "WHATSAPP_APP_SECRET" "App secret for webhook validation" "true"
    prompt_var "WHATSAPP_WEBHOOK_URL" "Public webhook URL" "false"
fi

# Additional AI providers (optional)
read -p "Configure additional AI providers? (y/N): " setup_ai
if [[ "$setup_ai" =~ ^[Yy]$ ]]; then
    print_status "INFO" "Setting up additional AI providers..."
    prompt_var "GEMINI_API_KEY" "Google Gemini API key" "true"
    prompt_var "GROQ_API_KEY" "Groq API key" "true"
    prompt_var "HUGGINGFACE_API_KEY" "Hugging Face API key" "true"
    prompt_var "OPENROUTER_API_KEY" "OpenRouter API key" "true"
fi

# Step 3: Create local environment file
print_header "Step 3: Create Local Environment"

ENV_FILE=".env"
BACKUP_FILE=".env.backup.$(date +%Y%m%d_%H%M%S)"

# Backup existing file
if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "$BACKUP_FILE"
    print_status "OK" "Backed up existing .env"
fi

# Create new .env file
print_status "INFO" "Creating Doppler-integrated .env file..."

cat > "$ENV_FILE" << 'EOL'
# Obsidian Bot Environment Configuration
# Generated by setup-doppler.sh
# Source: Doppler secrets management

# Database Configuration
TURSO_DATABASE_URL=\$(doppler secrets get TURSO_DATABASE_URL --plain)

# Bot Configuration
TELEGRAM_BOT_TOKEN=\$(doppler secrets get TELEGRAM_BOT_TOKEN --plain)
SESSION_SECRET=\$(doppler secrets get SESSION_SECRET --plain)
ENVIRONMENT_MODE=dev
AI_ENABLED=true

# AI Configuration
CLOUDFLARE_WORKER_URL=\$(doppler secrets get CLOUDFLARE_WORKER_URL --plain)
ACTIVE_PROVIDER=\$(doppler secrets get ACTIVE_PROVIDER --plain)

# Additional AI Providers
GEMINI_API_KEY=\$(doppler secrets get GEMINI_API_KEY --plain 2>/dev/null || echo "")
GROQ_API_KEY=\$(doppler secrets get GROQ_API_KEY --plain 2>/dev/null || echo "")
HUGGINGFACE_API_KEY=\$(doppler secrets get HUGGINGFACE_API_KEY --plain 2>/dev/null || echo "")
OPENROUTER_API_KEY=\$(doppler secrets get OPENROUTER_API_KEY --plain 2>/dev/null || echo "")

# WhatsApp Configuration
WHATSAPP_ACCESS_TOKEN=\$(doppler secrets get WHATSAPP_ACCESS_TOKEN --plain 2>/dev/null || echo "")
WHATSAPP_VERIFY_TOKEN=\$(doppler secrets get WHATSAPP_VERIFY_TOKEN --plain 2>/dev/null || echo "")
WHATSAPP_APP_SECRET=\$(doppler secrets get WHATSAPP_APP_SECRET --plain 2>/dev/null || echo "")
WHATSAPP_WEBHOOK_URL=\$(doppler secrets get WHATSAPP_WEBHOOK_URL --plain 2>/dev/null || echo "")
EOL

chmod 600 "$ENV_FILE"
print_status "OK" "Created Doppler-integrated .env file"

# Step 4: Create helper scripts
print_header "Step 4: Helper Scripts"

# Test script
cat > test-doppler.sh << 'EOL'
#!/bin/bash

echo "🧪 Doppler Environment Test"
echo "============================"

# Test environment loading
if source .env 2>/dev/null; then
    echo "✅ Environment loads successfully"
else
    echo "❌ Environment failed to load"
    exit 1
fi

# Test critical variables
echo ""
echo "🔑 Critical Variables:"
for var in "TURSO_DATABASE_URL" "SESSION_SECRET" "CLOUDFLARE_WORKER_URL" "TELEGRAM_BOT_TOKEN"; do
    if [ -n "${!var}" ]; then
        echo "✅ $var is set"
    else
        echo "❌ $var is missing"
    fi
done

# Test Doppler integration
echo ""
echo "🔗 Doppler Integration:"
if doppler whoami &> /dev/null; then
    echo "✅ Doppler authentication working"
else
    echo "❌ Doppler authentication failed"
fi

# Test Cloudflare Worker
if [ -n "$CLOUDFLARE_WORKER_URL" ]; then
    if curl -s --max-time 5 "$CLOUDFLARE_WORKER_URL/health" | grep -q "OK"; then
        echo "✅ Cloudflare Worker accessible"
    else
        echo "❌ Cloudflare Worker not accessible"
    fi
fi

echo ""
echo "🚀 Ready to start bot with: ./bot"
EOL

chmod +x test-doppler.sh
print_status "OK" "Created test-doppler.sh"

# Update script
cat > update-doppler.sh << 'EOL'
#!/bin/bash

echo "🔄 Updating Doppler secrets..."
doppler secrets sync --scope
echo "✅ Doppler secrets synchronized"

echo ""
echo "🔄 Restarting bot..."
if pgrep -f "bot" > /dev/null; then
    echo "Stopping existing bot..."
    pkill -f "bot"
    sleep 2
fi

./bot &
echo "✅ Bot started with updated configuration"
EOL

chmod +x update-doppler.sh
print_status "OK" "Created update-doppler.sh"

# Step 5: Final instructions
print_header "Setup Complete! 🎉"

echo -e "${GREEN}✅ Doppler environment setup completed successfully!${NC}"
echo ""
echo -e "${BLUE}🚀 Next Steps:${NC}"
echo "================================"
echo "1. ${YELLOW}Test your environment:${NC}"
echo "   ./test-doppler.sh"
echo ""
echo "2. ${YELLOW}Start the bot:${NC}"
echo "   ./bot"
echo ""
echo "3. ${YELLOW}Access dashboard:${NC}"
echo "   http://localhost:8080"
echo ""
echo "4. ${YELLOW}Update secrets:${NC}"
echo "   ./update-doppler.sh"
echo ""
echo -e "${BLUE}📚 Useful Commands:${NC}"
echo "  • List secrets:     doppler secrets list"
echo "  • Get secret:       doppler secrets get VAR_NAME"
echo "  • Set new secret:   doppler secrets set VAR_NAME value"
echo "  • Sync secrets:     doppler secrets sync"
echo ""
echo -e "${GREEN}🎯 Your environment is now properly configured with Doppler!${NC}"
EOL

chmod +x update-doppler.sh
print_status "OK" "Created update-doppler.sh"