openapi: 3.0.3
info:
  title: Branch Commit Review API
  description: API for comprehensive Git branch and commit analysis and review
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: https://api.branch-review.example.com/v1
    description: Production server
  - url: http://localhost:8080/v1
    description: Local development server

paths:
  /repositories/{repoId}/branches:
    get:
      summary: Get all branches for a repository
      description: Retrieve list of all branches with their current status
      parameters:
        - name: repoId
          in: path
          required: true
          schema:
            type: string
          description: Repository identifier (URL or ID)
        - name: status
          in: query
          schema:
            type: string
            enum: [active, stale, merged, deleted]
          description: Filter branches by status
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Maximum number of branches to return
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  branches:
                    type: array
                    items:
                      $ref: '#/components/schemas/Branch'
                  total:
                    type: integer
                  next:
                    type: string
                    description: Pagination token
        '404':
          description: Repository not found

  /repositories/{repoId}/branches/{branchName}/commits:
    get:
      summary: Get commits for a specific branch
      description: Retrieve paginated list of commits for a branch
      parameters:
        - name: repoId
          in: path
          required: true
          schema:
            type: string
        - name: branchName
          in: path
          required: true
          schema:
            type: string
        - name: since
          in: query
          schema:
            type: string
            format: date-time
          description: Only commits after this date
        - name: until
          in: query
          schema:
            type: string
            format: date-time
          description: Only commits before this date
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  commits:
                    type: array
                    items:
                      $ref: '#/components/schemas/Commit'
                  total:
                    type: integer
                  next:
                    type: string
        '404':
          description: Branch not found

  /reviews:
    post:
      summary: Start a new review
      description: Initiate a review session for branches or commits
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - targetType
                - targetIdentifier
                - reviewType
              properties:
                targetType:
                  type: string
                  enum: [branch, commit_range, repository]
                targetIdentifier:
                  type: string
                  description: Branch name, commit range, or repository URL
                reviewType:
                  type: string
                  enum: [individual, comprehensive, security]
                reviewer:
                  type: string
                  description: Name of the reviewer
      responses:
        '201':
          description: Review started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: Invalid request parameters

  /reviews/{reviewId}:
    get:
      summary: Get review status and results
      description: Retrieve current status and findings of a review
      parameters:
        - name: reviewId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Review details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Review not found

  /reviews/{reviewId}/report:
    get:
      summary: Download review report
      description: Get the generated report for a completed review
      parameters:
        - name: reviewId
          in: path
          required: true
          schema:
            type: string
        - name: format
          in: query
          schema:
            type: string
            enum: [html, pdf, json, sarif]
            default: html
          description: Report format
      responses:
        '200':
          description: Report file
          content:
            application/html:
              schema:
                type: string
            application/pdf:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: object
        '404':
          description: Review or report not found

  /webhooks/reviews:
    post:
      summary: Webhook for automated reviews
      description: Endpoint for CI/CD systems to trigger automated reviews
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - repository
                - event
              properties:
                repository:
                  type: string
                  description: Repository URL or identifier
                event:
                  type: string
                  enum: [push, pull_request, schedule]
                branch:
                  type: string
                  description: Branch name (for push/PR events)
                commitRange:
                  type: string
                  description: Commit range to review
                callbackUrl:
                  type: string
                  format: uri
                  description: URL to notify with results
      responses:
        '202':
          description: Review request accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  reviewId:
                    type: string
                  status:
                    type: string
                    enum: [queued]
                  estimatedDuration:
                    type: integer
                    description: Estimated completion time in seconds
        '400':
          description: Invalid webhook payload

components:
  schemas:
    Branch:
      type: object
      required:
        - id
        - name
        - repositoryUrl
        - status
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        repositoryUrl:
          type: string
          format: uri
        status:
          type: string
          enum: [active, stale, merged, deleted]
        lastCommitHash:
          type: string
        lastCommitDate:
          type: string
          format: date-time
        lastCommitAuthor:
          type: string
        aheadCount:
          type: integer
          minimum: 0
        behindCount:
          type: integer
          minimum: 0
        hasMergeConflicts:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Commit:
      type: object
      required:
        - id
        - hash
        - branchId
        - authorName
        - authorEmail
        - commitDate
        - message
      properties:
        id:
          type: string
          format: uuid
        hash:
          type: string
        branchId:
          type: string
          format: uuid
        authorName:
          type: string
        authorEmail:
          type: string
          format: email
        commitDate:
          type: string
          format: date-time
        message:
          type: string
        parentHashes:
          type: array
          items:
            type: string
        changedFiles:
          type: array
          items:
            type: string
        insertions:
          type: integer
          minimum: 0
        deletions:
          type: integer
          minimum: 0
        qualityScore:
          type: integer
          minimum: 0
          maximum: 100
        hasSecurityIssues:
          type: boolean
        isLargeCommit:
          type: boolean
        sensitiveDataFound:
          type: boolean
        createdAt:
          type: string
          format: date-time

    Review:
      type: object
      required:
        - id
        - targetType
        - targetIdentifier
        - reviewType
        - status
      properties:
        id:
          type: string
          format: uuid
        targetType:
          type: string
          enum: [branch, commit_range, repository]
        targetIdentifier:
          type: string
        reviewType:
          type: string
          enum: [individual, comprehensive, security]
        status:
          type: string
          enum: [pending, in_progress, completed, failed]
        startedAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
        totalCommits:
          type: integer
          minimum: 0
        issuesFound:
          type: integer
          minimum: 0
        criticalIssues:
          type: integer
          minimum: 0
        recommendations:
          type: array
          items:
            type: string
        reportUrl:
          type: string
          format: uri
        reviewer:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Issue:
      type: object
      required:
        - id
        - issueType
        - severity
        - description
      properties:
        id:
          type: string
          format: uuid
        reviewId:
          type: string
          format: uuid
        commitHash:
          type: string
        issueType:
          type: string
          enum: [security, quality, performance, documentation]
        severity:
          type: string
          enum: [critical, high, medium, low, info]
        category:
          type: string
        description:
          type: string
        filePath:
          type: string
        lineNumber:
          type: integer
          minimum: 1
        codeSnippet:
          type: string
        remediation:
          type: string
        toolName:
          type: string
        confidence:
          type: number
          minimum: 0.0
          maximum: 1.0
        createdAt:
          type: string
          format: date-time

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key