// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type ProcessedFile struct {
	ID            int64
	Hash          string
	Category      string
	Timestamp     time.Time
	ExtractedText sql.NullString
}
