// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const createFile = `-- name: CreateFile :one
INSERT INTO processed_files (
    hash,
    category
) VALUES (
    ?, ?
)
RETURNING id, hash, category, timestamp, extracted_text
`

type CreateFileParams struct {
	Hash     string
	Category string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (ProcessedFile, error) {
	row := q.db.QueryRowContext(ctx, createFile, arg.Hash, arg.Category)
	var i ProcessedFile
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Category,
		&i.Timestamp,
		&i.ExtractedText,
	)
	return i, err
}

const getFileByHash = `-- name: GetFileByHash :one
SELECT id, hash, category, timestamp, extracted_text FROM processed_files
WHERE hash = ?
`

func (q *Queries) GetFileByHash(ctx context.Context, hash string) (ProcessedFile, error) {
	row := q.db.QueryRowContext(ctx, getFileByHash, hash)
	var i ProcessedFile
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Category,
		&i.Timestamp,
		&i.ExtractedText,
	)
	return i, err
}

const getStats = `-- name: GetStats :one
SELECT
    (SELECT COUNT(*) FROM processed_files) AS total_files,
    (SELECT COUNT(*) FROM processed_files WHERE category = 'general') AS general_files,
    (SELECT COUNT(*) FROM processed_files WHERE category = 'unprocessed') AS unprocessed_files,
    (SELECT COUNT(*) FROM processed_files WHERE category = 'math') AS math_files,
    (SELECT COUNT(*) FROM processed_files WHERE category = 'physics') AS physics_files,
    (SELECT COUNT(*) FROM processed_files WHERE category = 'admin') AS admin_files
`

type GetStatsRow struct {
	TotalFiles       int64
	GeneralFiles     int64
	UnprocessedFiles int64
	MathFiles        int64
	PhysicsFiles     int64
	AdminFiles       int64
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(
		&i.TotalFiles,
		&i.GeneralFiles,
		&i.UnprocessedFiles,
		&i.MathFiles,
		&i.PhysicsFiles,
		&i.AdminFiles,
	)
	return i, err
}

const updateFileText = `-- name: UpdateFileText :exec
UPDATE processed_files
SET extracted_text = ?
WHERE hash = ?
`

type UpdateFileTextParams struct {
	ExtractedText sql.NullString
	Hash          string
}

func (q *Queries) UpdateFileText(ctx context.Context, arg UpdateFileTextParams) error {
	_, err := q.db.ExecContext(ctx, updateFileText, arg.ExtractedText, arg.Hash)
	return err
}
