// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package dashboard

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "obsidian-automation/internal/state"

func EnvironmentPanel(env state.EnvironmentState) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-[#111114] p-6 rounded-xl shadow-2xl border border-gray-800\"><h2 class=\"text-[10px] font-bold mb-6 flex items-center uppercase tracking-[0.2em] text-gray-500\"><span class=\"material-icons mr-2 text-yellow-500 text-sm\">bolt</span> Environment Management</h2><form @submit.prevent=\"\n\t\t\t\tconst data = {\n\t\t\t\t\tmode: $el.mode.value,\n\t\t\t\t\tbackendHost: $el.backendHost.value,\n\t\t\t\t\tisolationEnabled: $el.isolationEnabled.checked\n\t\t\t\t};\n\t\t\t\tfetch('/api/env/set', {\n\t\t\t\t\tmethod: 'POST',\n\t\t\t\t\theaders: { 'Content-Type': 'application/json' },\n\t\t\t\t\tbody: JSON.stringify(data)\n\t\t\t\t}).then(res => {\n\t\t\t\t\tif (res.ok) {\n\t\t\t\t\t\t$store.notifications.show('Environment updated successfully', 'success');\n\t\t\t\t\t} else {\n\t\t\t\t\t\t$store.notifications.show('Failed to update environment', 'error');\n\t\t\t\t\t}\n\t\t\t\t})\n\t\t\t\" class=\"space-y-6\"><div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\"><div class=\"space-y-2\"><label class=\"text-[9px] font-bold text-gray-500 uppercase\">Operational Mode</label> <select name=\"mode\" class=\"w-full p-3 bg-gray-900 border border-gray-800 rounded-lg text-white text-xs focus:ring-2 focus:ring-blue-500 outline-none transition-all\"><option value=\"prod\" selected=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(env.Mode == "prod")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/dashboard/environment_panel.templ`, Line: 36, Col: 56}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">Production</option> <option value=\"dev\" selected=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(env.Mode == "dev")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/dashboard/environment_panel.templ`, Line: 37, Col: 54}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">Development</option> <option value=\"staging\" selected=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(env.Mode == "staging")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/dashboard/environment_panel.templ`, Line: 38, Col: 62}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">Staging</option></select></div><div class=\"space-y-2\"><label class=\"text-[9px] font-bold text-gray-500 uppercase\">Backend Host</label> <input name=\"backendHost\" type=\"text\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(env.BackendHost)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/dashboard/environment_panel.templ`, Line: 43, Col: 66}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" class=\"w-full p-3 bg-gray-900 border border-gray-800 rounded-lg text-white text-xs focus:ring-2 focus:ring-blue-500 outline-none transition-all\"></div></div><div class=\"flex items-center space-x-3 p-4 bg-gray-900/50 rounded-lg border border-gray-800\"><input name=\"isolationEnabled\" type=\"checkbox\" id=\"iso-toggle\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if env.IsolationEnabled {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " checked")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, " class=\"w-4 h-4 rounded border-gray-700 bg-gray-800 text-blue-600 focus:ring-blue-500\"> <label for=\"iso-toggle\" class=\"text-xs text-gray-300\">Enable Environment Isolation</label><p class=\"text-[9px] text-gray-500 ml-auto\">Prevents cross-environment interference</p></div><button type=\"submit\" class=\"w-full bg-yellow-600 hover:bg-yellow-500 text-white p-3 rounded-lg transition-all font-bold text-[10px] uppercase tracking-widest flex items-center justify-center shadow-lg shadow-yellow-900/20\">Save Configuration</button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
