// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package dashboard

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" class=\"dark\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Login - Obsidian Bot</title><link href=\"https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap\" rel=\"stylesheet\"><link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\"><script src=\"https://cdn.tailwindcss.com\"></script></head><body class=\"bg-[#0a0a0c] text-gray-300 font-['JetBrains_Mono'] h-screen flex items-center justify-center\"><div class=\"bg-[#111114] p-8 rounded-2xl border border-gray-800 shadow-2xl w-full max-w-md text-center\"><div class=\"mb-8\"><span class=\"material-icons text-blue-500 text-5xl mb-4\">smart_toy</span><h1 class=\"text-xl font-bold text-white uppercase tracking-widest\">Obsidian Bot</h1><p class=\"text-gray-500 text-xs mt-2 uppercase tracking-tighter\">Secure Dashboard Access</p></div><div class=\"space-y-4\"><a href=\"/auth/google/login\" class=\"flex items-center justify-center space-x-3 bg-white hover:bg-gray-100 text-gray-900 font-bold py-3 px-6 rounded-xl transition-all duration-200 group\"><img src=\"https://www.google.com/favicon.ico\" class=\"w-5 h-5\" alt=\"Google\"> <span class=\"text-sm\">Sign in with Google</span></a> <a href=\"/auth/dev/login\" class=\"flex items-center justify-center space-x-3 bg-gray-800 hover:bg-gray-700 text-blue-400 font-bold py-3 px-6 rounded-xl transition-all duration-200 border border-blue-500/20\"><span class=\"material-icons text-sm\">terminal</span> <span class=\"text-sm\">Development Login</span></a><div class=\"pt-6 border-t border-gray-800\"><p class=\"text-[10px] text-gray-600 uppercase tracking-widest\">Authorized Personnel Only</p></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
