// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Instance struct {
	ID        int64     `json:"id"`
	Pid       int64     `json:"pid"`
	StartedAt time.Time `json:"started_at"`
}

type ProcessedFile struct {
	ID            int64          `json:"id"`
	Hash          string         `json:"hash"`
	Category      string         `json:"category"`
	Timestamp     time.Time      `json:"timestamp"`
	ExtractedText sql.NullString `json:"extracted_text"`
}
