// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createProcessedFile = `-- name: CreateProcessedFile :exec
INSERT INTO processed_files (hash, category, extracted_text)
VALUES (?, ?, ?)
`

type CreateProcessedFileParams struct {
	Hash          string         `json:"hash"`
	Category      string         `json:"category"`
	ExtractedText sql.NullString `json:"extracted_text"`
}

func (q *Queries) CreateProcessedFile(ctx context.Context, arg CreateProcessedFileParams) error {
	_, err := q.db.ExecContext(ctx, createProcessedFile, arg.Hash, arg.Category, arg.ExtractedText)
	return err
}
