openapi: 3.0.3
info:
  title: Direct Code Submission API
  description: API contracts for direct Manim code submission and validation
  version: 1.0.0

paths:
  /api/v1/code:
    post:
      summary: Submit direct Manim code
      description: Submit Manim animation code directly for rendering without AI processing
      tags:
        - Code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DirectCodeSubmission'
      responses:
        '202':
          description: Code queued for rendering
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobResponse'
        '400':
          description: Invalid code or request format
        '429':
          description: Rate limit exceeded

    get:
      summary: Validate Manim code syntax
      description: Check if provided Manim code is syntactically valid
      tags:
        - Code
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
            description: Manim code to validate
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodeValidationResponse'
        '400':
          description: Invalid code format

components:
  schemas:
    DirectCodeSubmission:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          minLength: 10
          maxLength: 50000
          description: Valid Python Manim code
        options:
          type: object
          properties:
            quality:
              type: string
              enum: [low, medium, high]
              default: medium
              description: Rendering quality level
            format:
              type: string
              enum: [mp4, webm]
              default: mp4
              description: Output video format
            max_duration_seconds:
              type: integer
              minimum: 1
              maximum: 300
              default: 30
              description: Maximum animation duration

    CodeValidationResponse:
      type: object
      properties:
        valid:
          type: boolean
          description: Whether the code is syntactically valid
        errors:
          type: array
          items:
            type: string
          description: Syntax or validation errors
        warnings:
          type: array
          items:
            type: string
          description: Non-critical issues or suggestions

    JobResponse:
      type: object
      properties:
        job_id:
          type: string
          format: uuid
          description: Unique job identifier
        status:
          type: string
          enum: [queued, processing, ready, failed]
          description: Current job status
        message:
          type: string
          description: Human-readable status message
        created_at:
          type: string
          format: date-time
          description: Job creation timestamp</content>
<parameter name="filePath">specs/006-ai-manim-video/contracts/direct-code-api.yaml