// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Mobile Header --><header class=\"bg-[#111114]/80 backdrop-blur-md sticky top-0 z-10 px-4 py-3 border-b border-gray-800 flex justify-between items-center lg:hidden\"><button @click=\"$store.app.toggleSidebar()\" class=\"text-gray-400 hover:text-white\"><span class=\"material-icons\">menu</span></button><h1 class=\"text-xs font-bold flex items-center text-white tracking-widest uppercase\"><span class=\"material-icons mr-2 text-blue-500 text-sm\">smart_toy</span> BOT</h1><div class=\"text-[10px] font-mono text-blue-500\">SYNC: <span x-text=\"$store.app.countdown\"></span>s</div></header><!-- Breadcrumbs / Top Bar (Desktop) --><div class=\"hidden lg:flex items-center px-8 py-4 border-b border-gray-800 bg-[#0a0a0c] text-gray-500 text-[10px] uppercase tracking-wider sticky top-0 z-10\"><span class=\"text-gray-600\">Home</span> <span class=\"mx-2 text-gray-700\">/</span> <span class=\"text-blue-500 font-bold\" x-text=\"$store.app.activeTab\">Control Center</span></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
