// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"obsidian-automation/internal/auth"
)

// Helper to get session from context (duplicated for now, or could be in a shared utils pkg)
func getSessionUser(ctx context.Context) *auth.UserSession {
	val := ctx.Value("session")
	if val == nil {
		return nil
	}
	return val.(*auth.UserSession)
}

func Layout(initialTab string, content templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" class=\"dark\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Obsidian Bot Dashboard</title><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><link href=\"https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap\" rel=\"stylesheet\"><link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\"><script src=\"https://cdn.tailwindcss.com\"></script><!-- Defer Alpine to ensure app.js loads first or concurrently but executes after --><script src=\"//unpkg.com/alpinejs\" defer></script><script src=\"https://unpkg.com/htmx.org@1.9.10\"></script><script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script><link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css\"><script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/toastify-js\"></script><link rel=\"stylesheet\" href=\"/static/style.css\"><!-- Load custom app logic --><script src=\"/static/app.js\"></script><script>\n        // Inject server-side initial state\n        window.initialTab = \"{ initialTab }\";\n    </script></head><body class=\"bg-[#0a0a0c] text-gray-300 font-['JetBrains_Mono'] text-xs selection:bg-blue-500/30\" x-data><div class=\"flex min-h-screen relative\"><!-- Mobile Sidebar Backdrop --><div x-show=\"$store.app.sidebarOpen\" x-transition.opacity @click=\"$store.app.toggleSidebar()\" class=\"fixed inset-0 bg-black/50 z-20 lg:hidden backdrop-blur-sm\"></div><!-- Sidebar Component -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Sidebar(getSessionUser(ctx)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!-- Main Content --><main class=\"flex-grow overflow-y-auto w-full\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div id=\"main-content\" class=\"p-4 lg:p-8 space-y-6 max-w-7xl mx-auto\" hx-trigger=\"refresh\" x-init=\"$store.app.syncUI()\"><!-- Content Injection -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><footer class=\"px-8 py-12 border-t border-gray-800 text-center space-y-2\"><div class=\"text-gray-600 font-bold uppercase tracking-[0.3em] text-[10px]\">Obsidian Bot Dashboard © 2026</div><div class=\"flex justify-center items-center space-x-4 text-[10px] text-gray-500\"><a href=\"/api/services/status\" target=\"_blank\" class=\"hover:text-blue-400 transition-colors\">SYSTEM_STATUS</a> <span class=\"text-gray-800\">/</span> <a href=\"https://github.com/yourusername/obsidian-bot\" target=\"_blank\" class=\"hover:text-blue-400 transition-colors\">SOURCE_CODE</a></div></footer></main></div><script>\n    // Global helper for HTMX polling logic, bridging to Alpine store\n    function shouldPoll() {\n        if (!Alpine || !Alpine.store('app')) return true;\n        return Alpine.store('app').shouldPoll();\n    }\n</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
